default['better-chef-rundeck']['user'] = 'better-chef-rundeck'
default['better-chef-rundeck']['group'] = 'better-chef-rundeck'
default['better-chef-rundeck']['install_directory'] = '/srv/better-chef-rundeck'
default['better-chef-rundeck']['git']['repository'] = 'https://github.com/atheiman/better-chef-rundeck.git'
default['better-chef-rundeck']['git']['revision'] = '00c75e277d71167a8f1e5a5f322e601f0021e76a'
default['better-chef-rundeck']['application']['environment'] = 'production'
default['better-chef-rundeck']['passenger_standalone']['port'] = '3000'
